import { PurchaseRecord, Vendor, StaffMember } from './types';

// Sample base64 SVG data urls for realistic visual attachments
const SAMPLE_RECEIPT_IMG =
  'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="500" viewBox="0 0 400 500"><rect width="400" height="500" fill="%23f8fafc"/><rect x="20" y="20" width="360" height="460" rx="8" fill="%23ffffff" stroke="%23cbd5e1" stroke-width="2"/><text x="200" y="60" font-family="sans-serif" font-size="16" font-weight="bold" fill="%230f172a" text-anchor="middle">ใบกำกับภาษี / ใบเสร็จรับเงิน</text><text x="200" y="85" font-family="sans-serif" font-size="12" fill="%2364748b" text-anchor="middle">บริษัท ขอนแก่น ไซแอนทิฟิค แอนด์ เคมีคอล จำกัด</text><line x1="40" y1="105" x2="360" y2="105" stroke="%23e2e8f0" stroke-width="1.5"/><rect x="40" y="125" width="200" height="12" rx="4" fill="%23e2e8f0"/><rect x="280" y="125" width="80" height="12" rx="4" fill="%23cbd5e1"/><rect x="40" y="150" width="180" height="12" rx="4" fill="%23e2e8f0"/><rect x="280" y="150" width="80" height="12" rx="4" fill="%23cbd5e1"/><rect x="40" y="175" width="220" height="12" rx="4" fill="%23e2e8f0"/><rect x="280" y="175" width="80" height="12" rx="4" fill="%23cbd5e1"/><line x1="40" y1="210" x2="360" y2="210" stroke="%23e2e8f0" stroke-width="1.5"/><text x="40" y="235" font-family="sans-serif" font-size="12" fill="%2364748b">ราคาก่อนภาษี (Subtotal)</text><text x="360" y="235" font-family="sans-serif" font-size="12" fill="%23334155" text-anchor="end">฿28,500.00</text><text x="40" y="255" font-family="sans-serif" font-size="12" fill="%2364748b">ภาษีมูลค่าเพิ่ม VAT 7%</text><text x="360" y="255" font-family="sans-serif" font-size="12" fill="%23334155" text-anchor="end">฿1,995.00</text><line x1="40" y1="270" x2="360" y2="270" stroke="%23cbd5e1" stroke-width="1"/><text x="40" y="295" font-family="sans-serif" font-size="14" font-weight="bold" fill="%230f172a">ยอดสุทธิรวม VAT</text><text x="360" y="295" font-family="sans-serif" font-size="14" font-weight="bold" fill="%23059669" text-anchor="end">฿30,495.00</text><rect x="240" y="380" width="120" height="50" rx="4" fill="%23ecfdf5" stroke="%236ee7b7"/><text x="300" y="410" font-family="sans-serif" font-size="12" fill="%23047857" text-anchor="middle">ตราประทับชำระเงิน</text></svg>';

const SAMPLE_SIGNED_PR_DOC =
  'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="500" viewBox="0 0 400 500"><rect width="400" height="500" fill="%23f1f5f9"/><rect x="20" y="20" width="360" height="460" rx="8" fill="%23ffffff" stroke="%2394a3b8" stroke-width="2"/><text x="200" y="55" font-family="sans-serif" font-size="15" font-weight="bold" fill="%231e293b" text-anchor="middle">บันทึกข้อความขออนุมัติจัดซื้อ (PR)</text><text x="200" y="78" font-family="sans-serif" font-size="11" fill="%23475569" text-anchor="middle">สาขาวิชาจุลชีววิทยา คณะแพทยศาสตร์ มข.</text><line x1="40" y1="95" x2="360" y2="95" stroke="%23cbd5e1" stroke-width="1.5"/><rect x="40" y="120" width="320" height="8" rx="2" fill="%23cbd5e1"/><rect x="40" y="138" width="300" height="8" rx="2" fill="%23e2e8f0"/><rect x="40" y="156" width="310" height="8" rx="2" fill="%23e2e8f0"/><rect x="40" y="174" width="240" height="8" rx="2" fill="%23e2e8f0"/><rect x="40" y="210" width="320" height="80" rx="6" fill="%23f8fafc" stroke="%23cbd5e1"/><text x="50" y="235" font-family="sans-serif" font-size="11" fill="%23334155">ตารางรายการพัสดุและราคาที่เสนอ</text><path d="M 120 400 Q 140 370 170 395 T 220 380" fill="none" stroke="%23059669" stroke-width="3"/><text x="170" y="420" font-family="sans-serif" font-size="10" fill="%23475569" text-anchor="middle">(ลงนามอนุมัติบนกระดาษเรียบร้อย)</text></svg>';

const SAMPLE_PHOTO_BOX =
  'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300" viewBox="0 0 400 300"><rect width="400" height="300" fill="%23f8fafc"/><rect x="50" y="60" width="300" height="180" rx="8" fill="%23ecfdf5" stroke="%2310b981" stroke-width="2"/><text x="200" y="150" font-family="sans-serif" font-size="14" font-weight="bold" fill="%23065f46" text-anchor="middle">📦 รูปถ่ายพัสดุ/อาหารเลี้ยงเชื้อที่ส่งถึงสาขาวิชา</text><text x="200" y="175" font-family="sans-serif" font-size="11" fill="%23047857" text-anchor="middle">ตรวจนับสภาพกล่องและควบคุมอุณหภูมิเรียบร้อย</text></svg>';

// 2. Initial Vendors Master List (คู่ค้า / บริษัทส่งตรวจและเวชภัณฑ์)
export const INITIAL_VENDORS: Vendor[] = [
  {
    id: 'ven-1',
    code: 'V-001',
    name: 'หจก. ขอนแก่น ไซแอนทิฟิค แอนด์ เคมีคอล',
    taxId: '0403557002199',
    phone: '043-241-555',
    address: '112/5 ถ.ศรีจันทร์ ต.ในเมือง อ.เมือง จ.ขอนแก่น 40000',
    contactPerson: 'คุณปิยะพงษ์ จุลเวช',
  },
  {
    id: 'ven-2',
    code: 'V-002',
    name: 'บจก. ไบโอเมดิคอล ลาบอราทอรี่ส์ (ขอนแก่น)',
    taxId: '0405561089221',
    phone: '043-306-789',
    address: '88/12 ถ.มิตรภาพ ต.ศิลา อ.เมือง จ.ขอนแก่น 40000',
    contactPerson: 'คุณเกศินี สุขเกษม',
  },
  {
    id: 'ven-3',
    code: 'V-003',
    name: 'บจก. เมดเทค ไซแอนซ์ อินสตรูเมนท์',
    taxId: '0105559033412',
    phone: '02-990-1200',
    address: '55/9 ถ.วิภาวดีรังสิต แขวงทุ่งสองห้อง เขตหลักสี่ กทม.',
    contactPerson: 'คุณสุชาติ เมดเทค',
  },
  {
    id: 'ven-4',
    code: 'V-004',
    name: 'บจก. เคเคยู สเตชั่นเนอรี่ แอนด์ ซัพพลาย',
    taxId: '0405558001234',
    phone: '043-202-889',
    address: '123/4 ถ.กัลปพฤกษ์ มหาวิทยาลัยขอนแก่น จ.ขอนแก่น 40002',
    contactPerson: 'คุณอิทธิกร พัสดุ',
  },
  {
    id: 'ven-5',
    code: 'V-005',
    name: 'บจก. ไทยไมโครไบโอ ซิสเต็มส์',
    taxId: '0105562098441',
    phone: '02-889-4455',
    address: '108 อาคารชีวการแพทย์ ชั้น 8 ถ.พญาไท ราชเทวี กทม. 10400',
    contactPerson: 'คุณกานต์ เจริญแล็บ',
  },
  {
    id: 'ven-6',
    code: 'V-006',
    name: 'ร้าน ขอนแก่น เมดิคอล เซอร์วิส แอนด์ ซัพพลาย',
    taxId: '3409900128741',
    phone: '081-554-9988',
    address: '45 ถ.หลังศูนย์ราชการ ต.ในเมือง อ.เมือง จ.ขอนแก่น',
    contactPerson: 'ช่างเอกชัย ซ่อมบำรุง',
  },
];

// 3. Initial Material Subtypes (หมวดวัสดุย่อยทางการแพทย์และวิทยาศาสตร์)
export const INITIAL_MATERIAL_SUBTYPES: string[] = [
  'วัสดุวิทยาศาสตร์และการแพทย์ (สารเคมี/อาหารเลี้ยงเชื้อ)',
  'วัสดุห้องปฏิบัติการและเครื่องแก้ว',
  'วัสดุสำนักงาน',
  'วัสดุงานบ้านและทำความสะอาดฆ่าเชื้อ',
  'วัสดุคอมพิวเตอร์และสารสนเทศ',
  'วัสดุการเรียนการสอนและการวิจัย',
  'วัสดุงานซ่อมบำรุงและเครื่องมือแพทย์',
];

// 4. Initial Staff Master List (อาจารย์และบุคลากร สาขาวิชาจุลชีววิทยา คณะแพทยศาสตร์ มข.)
export const INITIAL_STAFF_MEMBERS: StaffMember[] = [
  {
    id: 'staff-1',
    name: 'ศ.ดร.พญ.พัชรี สุริยะ',
    position: 'หัวหน้าสาขาวิชาจุลชีววิทยา',
    department: 'สาขาวิชาจุลชีววิทยา คณะแพทยศาสตร์ มหาวิทยาลัยขอนแก่น',
    role: 'all',
  },
  {
    id: 'staff-2',
    name: 'รศ.ดร.วิโรจน์ แพทย์จุลชีววิทยา',
    position: 'อาจารย์ประจำสาขา / ประธานหลักสูตร',
    department: 'สาขาวิชาจุลชีววิทยา คณะแพทยศาสตร์ มหาวิทยาลัยขอนแก่น',
    role: 'tor',
  },
  {
    id: 'staff-3',
    name: 'ผศ.ดร.กานดา รัตนเวชศาสตร์',
    position: 'อาจารย์ประจำสาขา / หัวหน้าห้องปฏิบัติการวิจัย',
    department: 'สาขาวิชาจุลชีววิทยา คณะแพทยศาสตร์ มหาวิทยาลัยขอนแก่น',
    role: 'tor',
  },
  {
    id: 'staff-4',
    name: 'นางสมพร สุขเกษม',
    position: 'นักวิทยาศาสตร์การแพทย์ชำนาญการ',
    department: 'สาขาวิชาจุลชีววิทยา คณะแพทยศาสตร์ มหาวิทยาลัยขอนแก่น',
    role: 'price',
  },
  {
    id: 'staff-5',
    name: 'นายสมศักดิ์ วงศ์สวัสดิ์',
    position: 'นักวิชาการพัสดุชำนาญการ',
    department: 'งานพัสดุ คณะแพทยศาสตร์ มหาวิทยาลัยขอนแก่น',
    role: 'inspector',
  },
  {
    id: 'staff-6',
    name: 'นางสุภาพร บุญมา',
    position: 'เจ้าหน้าที่ธุรการชำนาญงาน',
    department: 'สาขาวิชาจุลชีววิทยา คณะแพทยศาสตร์ มหาวิทยาลัยขอนแก่น',
    role: 'price',
  },
  {
    id: 'staff-7',
    name: 'นายธนาธิป เจริญทรัพย์',
    position: 'นักวิชาการคอมพิวเตอร์',
    department: 'หน่วยสารสนเทศ คณะแพทยศาสตร์ มหาวิทยาลัยขอนแก่น',
    role: 'inspector',
  },
];

// Initial Purchase Records (Fiscal Year 2568)
export const INITIAL_PURCHASE_RECORDS: PurchaseRecord[] = [
  {
    id: 'rec-2568-001',
    prNumber: 'PR-68-001',
    title: 'จัดซื้ออาหารเลี้ยงเชื้อแบคทีเรีย Blood Agar และสารเคมีวินิจฉัยทางจุลชีววิทยาการแพทย์',
    requestDate: '2025-01-15',
    deliveryDueDate: '2025-01-25',
    requester: 'ผศ.ดร.กานดา รัตนเวชศาสตร์',
    department: 'สาขาวิชาจุลชีววิทยา คณะแพทยศาสตร์ มหาวิทยาลัยขอนแก่น',
    category: 'material',
    materialSubType: 'วัสดุวิทยาศาสตร์และการแพทย์ (สารเคมี/อาหารเลี้ยงเชื้อ)',
    budgetSource: 'เงินรายได้สาขาวิชา',
    fiscalYear: 2568,
    mhesiNumber: 'อว 6603.10.1/0142',
    mhesiDate: '2025-01-16',
    vendorCode: 'V-001',
    vendorName: 'หจก. ขอนแก่น ไซแอนทิฟิค แอนด์ เคมีคอล',
    torMaker: 'ผศ.ดร.กานดา รัตนเวชศาสตร์',
    priceEstimator: 'นางสมพร สุขเกษม',
    inspectorName: 'นายสมศักดิ์ วงศ์สวัสดิ์',
    inspectionDocNumber: 'ตรวจรับที่ 08/2568',
    purNumber: 'PUR-68-001',
    rfqNumber: 'RFQ-68-0082',
    vatType: 'included',
    subtotalBeforeVat: 28500.0,
    vatAmount: 1995.0,
    totalAmount: 30495.0,
    items: [
      {
        id: 'it-1',
        code: 'MED-BA01',
        name: 'อาหารเลี้ยงเชื้อ Sheep Blood Agar Plate สำเร็จรูป (50 แผ่น/กล่อง)',
        quantity: 10,
        unit: 'กล่อง',
        unitPrice: 1650,
        totalPrice: 16500,
      },
      {
        id: 'it-2',
        code: 'CHEM-GR02',
        name: 'ชุดสีย้อม Gram Stain Kit พร้อมบัฟเฟอร์มาตรฐาน',
        quantity: 10,
        unit: 'ชุด',
        unitPrice: 1200,
        totalPrice: 12000,
      },
    ],
    status: 'inspected',
    inspectedDate: '2025-01-22',
    inspectedBy: 'นายสมศักดิ์ วงศ์สวัสดิ์ (นักวิชาการพัสดุ)',
    inspectionNote: 'ตรวจนับของแล้ว สภาพกล่องสมบูรณ์ มีการควบคุมอุณหภูมิระหว่างขนส่ง ครบถ้วนตามรายการ นำเข้าตู้เย็น 4°C เรียบร้อย',
    attachments: [
      {
        id: 'att-1',
        name: 'ใบเสร็จรับเงิน_INV-68019.jpg',
        size: 245000,
        type: 'image/jpeg',
        dataUrl: SAMPLE_RECEIPT_IMG,
        category: 'receipt',
        uploadedAt: '2025-01-22 14:30',
      },
      {
        id: 'att-2',
        name: 'รูปถ่ายกล่องอาหารเลี้ยงเชื้อ.jpg',
        size: 389000,
        type: 'image/jpeg',
        dataUrl: SAMPLE_PHOTO_BOX,
        category: 'photo',
        uploadedAt: '2025-01-22 14:35',
      },
    ],
    notes: 'เบิกจ่ายงบวัสดุวิทยาศาสตร์และการแพทย์ ประจำภาคการศึกษาที่ 2/2567',
    createdAt: '2025-01-15T09:00:00.000Z',
    updatedAt: '2025-01-22T14:40:00.000Z',
  },
  {
    id: 'rec-2568-002',
    prNumber: 'PR-68-002',
    title: 'จัดซื้อเครื่องปั่นเหวี่ยงตกตะกอนควบคุมอุณหภูมิความเร็วสูง (Refrigerated Microcentrifuge) 1 เครื่อง',
    requestDate: '2025-02-03',
    deliveryDueDate: '2025-03-20',
    requester: 'รศ.ดร.วิโรจน์ แพทย์จุลชีววิทยา',
    department: 'สาขาวิชาจุลชีววิทยา คณะแพทยศาสตร์ มหาวิทยาลัยขอนแก่น',
    category: 'asset',
    budgetSource: 'งบประมาณแผ่นดิน (งบลงทุน)',
    fiscalYear: 2568,
    mhesiNumber: 'อว 6603.10.1/0201',
    mhesiDate: '2025-02-04',
    vendorCode: 'V-003',
    vendorName: 'บจก. เมดเทค ไซแอนซ์ อินสตรูเมนท์',
    torMaker: 'รศ.ดร.วิโรจน์ แพทย์จุลชีววิทยา',
    priceEstimator: 'นางสมพร สุขเกษม',
    inspectorName: 'นายสมศักดิ์ วงศ์สวัสดิ์',
    inspectionDocNumber: '-',
    purNumber: 'PUR-68-002',
    rfqNumber: 'RFQ-68-0095',
    vatType: 'included',
    subtotalBeforeVat: 196261.68,
    vatAmount: 13738.32,
    totalAmount: 210000,
    items: [
      {
        id: 'it-3',
        code: 'EQ-CENT01',
        name: 'Refrigerated Microcentrifuge ความเร็วสูงสุด 15,000 rpm พร้อม Rotor 24 ช่อง',
        quantity: 1,
        unit: 'เครื่อง',
        unitPrice: 210000,
        totalPrice: 210000,
      },
    ],
    status: 'pending_inspection',
    inspectionNote: 'เครื่องส่งถึงห้องปฏิบัติการวิจัยชั้น 4 อาคารเรียนรวมแล้ว นัดช่างและอาจารย์ร่วมทดสอบระบบความเย็นและการปั่นรอบวันศุกร์นี้',
    attachments: [
      {
        id: 'att-3',
        name: 'บันทึกขอจัดซื้อ_PR-68-002_อนุมัติ.pdf',
        size: 420000,
        type: 'application/pdf',
        dataUrl: SAMPLE_SIGNED_PR_DOC,
        category: 'pr_file',
        uploadedAt: '2025-02-03 10:15',
      },
      {
        id: 'att-4',
        name: 'รูปถ่ายตัวเครื่องCentrifuge.jpg',
        size: 512000,
        type: 'image/jpeg',
        dataUrl: SAMPLE_PHOTO_BOX,
        category: 'photo',
        uploadedAt: '2025-02-18 11:20',
      },
    ],
    notes: 'ครุภัณฑ์ประจำห้องปฏิบัติการชีววิทยาโมเลกุลทางการแพทย์',
    createdAt: '2025-02-03T09:30:00.000Z',
    updatedAt: '2025-02-18T11:25:00.000Z',
  },
  {
    id: 'rec-2568-003',
    prNumber: 'PR-68-003',
    title: 'จัดซื้อน้ำยาฆ่าเชื้อเกรดการแพทย์ ถุงขยะติดเชื้อสีแดง และแอลกอฮอล์ 70% (วัสดุงานบ้าน/สุขอนามัย)',
    requestDate: '2025-02-10',
    deliveryDueDate: '2025-02-18',
    requester: 'นางสุภาพร บุญมา (เจ้าหน้าที่ธุรการสาขาวิชา)',
    department: 'สาขาวิชาจุลชีววิทยา คณะแพทยศาสตร์ มหาวิทยาลัยขอนแก่น',
    category: 'material',
    materialSubType: 'วัสดุงานบ้านและทำความสะอาดฆ่าเชื้อ',
    budgetSource: 'เงินรายได้สาขาวิชา',
    fiscalYear: 2568,
    mhesiNumber: '-',
    mhesiDate: '-',
    vendorCode: 'V-004',
    vendorName: 'บจก. เคเคยู สเตชั่นเนอรี่ แอนด์ ซัพพลาย',
    torMaker: 'นางสุภาพร บุญมา',
    priceEstimator: 'นางสุภาพร บุญมา',
    inspectorName: 'นายสมศักดิ์ วงศ์สวัสดิ์',
    inspectionDocNumber: 'ตรวจรับที่ 11/2568',
    purNumber: 'PUR-68-003',
    rfqNumber: '-',
    vatType: 'included',
    subtotalBeforeVat: 11214.95,
    vatAmount: 785.05,
    totalAmount: 12000,
    items: [
      {
        id: 'it-4',
        code: 'MED-DIS01',
        name: 'น้ำยาฆ่าเชื้อเกรดห้องปฏิบัติการจุลชีววิทยา แกลลอน 5 ลิตร',
        quantity: 8,
        unit: 'แกลลอน',
        unitPrice: 650,
        totalPrice: 5200,
      },
      {
        id: 'it-5',
        code: 'ALC-70',
        name: 'เอทิลแอลกอฮอล์ 70% v/v ขนาด 4,000 มล.',
        quantity: 10,
        unit: 'แกลลอน',
        unitPrice: 480,
        totalPrice: 4800,
      },
      {
        id: 'it-6',
        code: 'BIO-BAG',
        name: 'ถุงขยะติดเชื้อสีแดง มีสัญลักษณ์ชีวภาพ Biohazard (50 ใบ/แพ็ค)',
        quantity: 20,
        unit: 'แพ็ค',
        unitPrice: 100,
        totalPrice: 2000,
      },
    ],
    status: 'inspected',
    inspectedDate: '2025-02-16',
    inspectedBy: 'นายสมศักดิ์ วงศ์สวัสดิ์',
    inspectionNote: 'นับของครบถ้วน น้ำยาฆ่าเชื้อ 8 แกลลอน แอลกอฮอล์ 10 แกลลอน ถุงขยะติดเชื้อ 20 แพ็ค จัดเก็บในห้องเก็บพัสดุสาขาเรียบร้อย',
    attachments: [
      {
        id: 'att-5',
        name: 'ใบเสร็จรับเงิน_วัสดุทำความสะอาด.jpg',
        size: 198000,
        type: 'image/jpeg',
        dataUrl: SAMPLE_RECEIPT_IMG,
        category: 'receipt',
        uploadedAt: '2025-02-16 15:00',
      },
    ],
    notes: 'สำหรับควบคุมความปลอดภัยทางชีวภาพ (Biosafety) ในห้องปฏิบัติการ',
    createdAt: '2025-02-10T10:00:00.000Z',
    updatedAt: '2025-02-16T15:10:00.000Z',
  },
  {
    id: 'rec-2568-004',
    prNumber: 'PR-68-004',
    title: 'จัดซื้อชุดตรวจวิเคราะห์และสารเรืองแสงสำหรับการย้อมตรวจทางภูมิคุ้มกัน (Immunofluorescence Assay)',
    requestDate: '2025-02-20',
    deliveryDueDate: '2026-09-15', // Near due date alert!
    requester: 'ศ.ดร.พญ.พัชรี สุริยะ',
    department: 'สาขาวิชาจุลชีววิทยา คณะแพทยศาสตร์ มหาวิทยาลัยขอนแก่น',
    category: 'material',
    materialSubType: 'วัสดุวิทยาศาสตร์และการแพทย์ (สารเคมี/อาหารเลี้ยงเชื้อ)',
    budgetSource: 'เงินรายได้คณะแพทยศาสตร์',
    fiscalYear: 2568,
    mhesiNumber: 'อว 6603.10.1/0288',
    mhesiDate: '2025-02-21',
    vendorCode: 'V-005',
    vendorName: 'บจก. ไทยไมโครไบโอ ซิสเต็มส์',
    torMaker: 'ศ.ดร.พญ.พัชรี สุริยะ',
    priceEstimator: 'นางสมพร สุขเกษม',
    inspectorName: 'นายสมศักดิ์ วงศ์สวัสดิ์',
    inspectionDocNumber: '-',
    purNumber: 'PUR-68-004',
    rfqNumber: 'RFQ-68-0120',
    vatType: 'included',
    subtotalBeforeVat: 44859.81,
    vatAmount: 3140.19,
    totalAmount: 48000,
    items: [
      {
        id: 'it-7',
        code: 'IFA-KIT01',
        name: 'IFA Detection Kit สำหรับการตรวจแอนติบอดีในผู้ป่วยวิจัย (96 tests/kit)',
        quantity: 2,
        unit: 'ชุด',
        unitPrice: 24000,
        totalPrice: 48000,
      },
    ],
    status: 'ordering',
    attachments: [
      {
        id: 'att-6',
        name: 'ใบPR-68-004_ลงนามแล้ว.pdf',
        size: 340000,
        type: 'application/pdf',
        dataUrl: SAMPLE_SIGNED_PR_DOC,
        category: 'pr_file',
        uploadedAt: '2025-02-20 16:20',
      },
    ],
    notes: 'บริษัทแจ้งส่งพัสดุทางระบบ Cold-chain คาดว่าจะส่งถึงภายในกำหนด',
    createdAt: '2025-02-20T11:00:00.000Z',
    updatedAt: '2025-02-20T16:25:00.000Z',
  },
  {
    id: 'rec-2568-005',
    prNumber: 'PR-68-005',
    title: 'จัดซื้อจานเพาะเชื้อสเตอร์ไรล์ Disposable Petri Dishes และ Micropipette Tips ชนิดกรอง (Filter Tips)',
    requestDate: '2025-02-25',
    deliveryDueDate: '2026-09-12', // Near due tomorrow alert!
    requester: 'นางสมพร สุขเกษม (นักวิทยาศาสตร์การแพทย์)',
    department: 'สาขาวิชาจุลชีววิทยา คณะแพทยศาสตร์ มหาวิทยาลัยขอนแก่น',
    category: 'material',
    materialSubType: 'วัสดุห้องปฏิบัติการและเครื่องแก้ว',
    budgetSource: 'เงินรายได้สาขาวิชา',
    fiscalYear: 2568,
    mhesiNumber: '-',
    mhesiDate: '-',
    vendorCode: 'V-002',
    vendorName: 'บจก. ไบโอเมดิคอล ลาบอราทอรี่ส์ (ขอนแก่น)',
    torMaker: 'นางสมพร สุขเกษม',
    priceEstimator: 'นางสุภาพร บุญมา',
    inspectorName: 'นายสมศักดิ์ วงศ์สวัสดิ์',
    inspectionDocNumber: '-',
    purNumber: '-',
    rfqNumber: '-',
    vatType: 'included',
    subtotalBeforeVat: 18224.3,
    vatAmount: 1275.7,
    totalAmount: 19500,
    items: [
      {
        id: 'it-8',
        code: 'PETRI-90',
        name: 'จานเพาะเชื้อพลาสติก Sterile Petri Dishes ขนาด 90x15 มม. (500 ใบ/ลัง)',
        quantity: 3,
        unit: 'ลัง',
        unitPrice: 2500,
        totalPrice: 7500,
      },
      {
        id: 'it-9',
        code: 'TIP-F200',
        name: 'Aerosol Barrier Filter Tips ขนาด 200 µL ปลอดเชื้อ (10 racks/pack)',
        quantity: 4,
        unit: 'pack',
        unitPrice: 3000,
        totalPrice: 12000,
      },
    ],
    status: 'pending_inspection',
    inspectionNote: 'ขนส่งนำพัสดุมาส่งที่ห้องธุรการสาขาวิชาแล้ว รอตรวจนับ Lot Number และวันหมดอายุ',
    attachments: [
      {
        id: 'att-7',
        name: 'รูปถ่ายกล่องจานเพาะเชื้อ.jpg',
        size: 210000,
        type: 'image/jpeg',
        dataUrl: SAMPLE_PHOTO_BOX,
        category: 'photo',
        uploadedAt: '2025-02-26 13:10',
      },
    ],
    notes: 'สำหรับฝึกปฏิบัตินักศึกษาแพทย์ชั้นปีที่ 2 และ 3 ในวิชาจุลชีววิทยาการแพทย์',
    createdAt: '2025-02-25T08:45:00.000Z',
    updatedAt: '2025-02-26T13:15:00.000Z',
  },
];
